# Multiple-Variable Linear Regression

Source: [Starting With Linear Regression in Python](https://realpython.com/courses/python-linear-regression/)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression

sns.set_style("darkgrid")

## Dummy data

In [2]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]

In [3]:
x = np.array(x)
y = np.array(y)

## Fit the model

In [4]:
model = LinearRegression().fit(x, y)

In [5]:
model.intercept_

5.52257927519819

In [7]:
model.coef_

array([0.44706965, 0.25502548])

In [8]:
model.score(x, y)

0.8615939258756775

In [9]:
y_predicted = model.predict(x)

In [10]:
y_predicted

array([ 5.77760476,  8.012953  , 12.73867497, 17.9744479 , 23.97529728,
       29.4660957 , 38.78227633, 41.27265006])

In [11]:
y, y_predicted

(array([ 4,  5, 20, 14, 32, 22, 38, 43]),
 array([ 5.77760476,  8.012953  , 12.73867497, 17.9744479 , 23.97529728,
        29.4660957 , 38.78227633, 41.27265006]))

In [12]:
new_observations = np.arange(10).reshape((-1, 2))
new_observations

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
y_predicted = model.predict(new_observations)
y_predicted

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])