# Multi-Variable Polynomial Regression

Source: [Starting With Linear Regression in Python](https://realpython.com/courses/python-linear-regression/)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

sns.set_style("darkgrid")

## Dummy data

In [2]:
x = np.array([[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]])
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [3]:
y = np.array([4, 5, 20, 14, 32, 22, 38, 43])
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [4]:
x_polynomial = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)
x_polynomial

array([[0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00],
       [5.000e+00, 1.000e+00, 2.500e+01, 5.000e+00, 1.000e+00],
       [1.500e+01, 2.000e+00, 2.250e+02, 3.000e+01, 4.000e+00],
       [2.500e+01, 5.000e+00, 6.250e+02, 1.250e+02, 2.500e+01],
       [3.500e+01, 1.100e+01, 1.225e+03, 3.850e+02, 1.210e+02],
       [4.500e+01, 1.500e+01, 2.025e+03, 6.750e+02, 2.250e+02],
       [5.500e+01, 3.400e+01, 3.025e+03, 1.870e+03, 1.156e+03],
       [6.000e+01, 3.500e+01, 3.600e+03, 2.100e+03, 1.225e+03]])

## Fit a linear regression model with multiple variables: z1=x1, z2=x2, z3=x1^2, z4=x1*x2, z5=x2^2

In [5]:
model = LinearRegression().fit(x_polynomial, y)
model

LinearRegression()

In [9]:
print(f"b0 = {model.intercept_}")

b0 = 0.8430556452395876


In [10]:
print(f"[b_1, b_2, b_3, b_4, b_5] = {model.coef_}")

[b_1, b_2, b_3, b_4, b_5] = [ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]


In [8]:
model.score(x_polynomial, y)

0.9453701449127822

In [23]:
y_predicted = model.predict(x_polynomial)
y_predicted.reshape((-1, 1))

array([[ 0.54047408],
       [11.36340283],
       [16.07809622],
       [15.79139   ],
       [29.73858619],
       [23.50834636],
       [39.05631386],
       [41.92339046]])

In [25]:
# Predict by hand by running the polynomial math
y_predicted_by_hand = model.intercept_ + x_polynomial.dot(np.array(model.coef_).reshape((-1, 1)))
y_predicted_by_hand

array([[ 0.54047408],
       [11.36340283],
       [16.07809622],
       [15.79139   ],
       [29.73858619],
       [23.50834636],
       [39.05631386],
       [41.92339046]])

In [28]:
np.testing.assert_array_equal(y_predicted.reshape((-1, 1)), y_predicted_by_hand)