# A very simple Neural Network

Source: [Building a Neural Network & Making Predictions With Python AI](https://realpython.com/courses/build-neural-network-python-ai/)

![My first neural network](./my-first-neural-network.png)

In [32]:
import numpy as np

# Implement the Sigmoid function

In [33]:
def sigmoid(x: np.array) -> np.array:
    """
    Sigmoid function
    :param x: Input vector
    :return: Sigmoid-transformed vector
    """
    return 1 / (1 + np.exp(-x))

In [34]:
test_vector = np.array([1, 2, 3, 4, 5])
sigmoid(test_vector)

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715])

In [35]:
(1 / (1 + np.exp(-test_vector)))

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715])

In [36]:
(1 / (1 + np.exp(-test_vector)) == sigmoid(test_vector)).all()

True

# Build a simple neural network

## First layer

In [41]:
def layer_1(input_vector: np.array, input_weights: np.array, bias: np.array) -> np.array:
    """
    Implements the first layer of the neural network
    :param input_vector: Input vector
    :param input_weights: Input weights
    :param bias: Bias
    :return: Fist layer's output
    """
    return np.dot(input_vector, input_weights) + bias

In [103]:
test_input_vector_1 = np.array([1.66, 1.56])

# Weights with random values to start with
test_weights_1 = np.array([1.45, -0.66])

test_bias = np.array([0.0])

In [104]:
layer_1(test_input_vector_1, test_weights_1, test_bias)

array([1.3774])

## Second and final (output) layer

In [105]:
def layer_2(input_vector: np.array) -> np.array:
    """
    Implements the second layer of the neural network
    :param input_vector: Input vector
    :return: Second layer's output
    """
    return sigmoid(input_vector)

# Run the model to predict

In [106]:
def predict(input_vector: np.array, weights_1: np.array, bias: np.array) -> np.array:
    """
    Predict.
    :param input_vector: Input vector.
    :param weights_1: Layer 1's weights.
    :param bias: Bias.
    :return: Prediction
    """
    return layer_2(layer_1(input_vector, weights_1, bias))

In [107]:
predict(test_input_vector_1, test_weights_1, test_bias)

array([0.7985731])

In [108]:
test_input_vector_2 = np.array([2, 1.5])
predict(test_input_vector_2, test_weights_1, test_bias)

array([0.87101915])

# Loss function

In [131]:
def mean_squared_error(prediction: np.array, target: np.array) -> np.array:
    """
    Computes the mean squared error of a prediction.
    :param prediction: Prediction
    :param target: target
    :return: Mean squared error
    """
    return np.square(prediction - target)

In [132]:
target = np.array([1])
prediction = predict(test_input_vector_1, test_weights_1, test_bias)
error = mean_squared_error(target, prediction)
print(f"input={test_input_vector_1}, target={target}, prediction={prediction}, error={error}")

input=[1.66 1.56], target=[1], prediction=[0.7985731], error=[0.04057279]


In [133]:
target = np.array([0])
prediction = predict(test_input_vector_2, test_weights_1, test_bias)
error = mean_squared_error(target, prediction)
print(f"input={test_input_vector_2}, target={target}, prediction={prediction}, error={error}")

input=[2.  1.5], target=[0], prediction=[0.87101915], error=[0.75867436]


# Implement a simple "gradient descent" to minimize the loss function

## "Gradient": Derivative of the loss function

In [134]:
def loss_function_derivative(prediction: np.array, target: np.array, learning_rate: np.array) -> np.array:
    """
    Computes the derivative of the loss function.
    :param prediction: Prediction
    :param target: Target
    :param learning_rate: Learning rate
    :return: Derivative of the loss function.
    """
    return 2 * (prediction - target) * learning_rate

## Adjust the weights

In [135]:
gradient_descent = loss_function_derivative(np.array([0]), predict(test_input_vector_2, test_weights_1, test_bias), np.array([0.1]))
gradient_descent

array([-0.17420383])

In [136]:
test_weights_1 - gradient_descent

array([ 1.62420383, -0.48579617])

## Predict again with the updated weights

In [137]:
test_weights_1 - gradient_descent

array([ 1.62420383, -0.48579617])

In [138]:
target = np.array([0])
prediction = predict(test_input_vector_2, test_weights_1 - gradient_descent, test_bias)
error = mean_squared_error(target, prediction)
print(f"input={test_input_vector_2}, target={target}, prediction={prediction}, error={error}")

input=[2.  1.5], target=[0], prediction=[0.9255123], error=[0.85657302]


In [139]:
target = np.array([1])
prediction = predict(test_input_vector_1, test_weights_1 - gradient_descent, test_bias)
error = mean_squared_error(target, prediction)
print(f"input={test_input_vector_1}, target={target}, prediction={prediction}, error={error}")

input=[1.66 1.56], target=[1], prediction=[0.87416926], error=[0.01583338]
